// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication12ayalabeeer.Models;

public partial class Group
{
    public int GroupId { get; set; }

    public string GroupName { get; set; }

    public int? Course { get; set; }

    public string Speciality { get; set; }
}