// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication12ayalabeeer.Models;

public partial class Subject
{
    public int SubjectId { get; set; }

    public string SubjectName { get; set; }

    public int TeacherId { get; set; }
}