// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication12ayalabeeer.Models;

public partial class Teacher
{
    public int TeacherId { get; set; }

    public string Name { get; set; }

    public string Department { get; set; }
}